export const getInitialHistory = () => [
  {
    id: "mock-1",
    name: "Dorothy",
    title: "Dorothy's Morning Chat",
    timestamp: new Date().toISOString(),
    duration: "12m 40s",
    mood: "Positive",
    moodEmoji: "😊",
    summary: "Dorothy talked about her gardening and confirmed she took her meds. She's looking forward to the weekend visit.",
    transcript: "Dorothy: Hello\nAI: Good morning Dorothy, how are you today?\nDorothy: I am doing well, just finished in the garden.\nAI: That sounds lovely! Did you remember to take your medication?\nDorothy: Yes, I took it right after breakfast.",
    flagged: false,
  },
  {
    id: "mock-2",
    name: "Dorothy",
    title: "Dorothy's Afternoon Check-in",
    timestamp: new Date(Date.now() - 86400000).toISOString(),
    duration: "8m 15s",
    mood: "Neutral",
    moodEmoji: "😐",
    summary: "Dorothy mentioned feeling slightly dizzy, she is monitoring her blood pressure.",
    transcript: "Dorothy: Hello\nAI: Good afternoon Dorothy, how are you feeling?\nDorothy: I've been feeling a bit dizzy this afternoon.\nAI: I'm sorry to hear that. Have you checked your blood pressure?\nDorothy: Yes, it was a little high, but I am resting now.",
    flagged: true,
  },
  {
    id: "mock-3",
    name: "Dorothy",
    title: "Dorothy's Weekly Catch-up",
    timestamp: new Date(Date.now() - 86400000 * 3).toISOString(),
    duration: "25m 02s",
    mood: "Good",
    moodEmoji: "😊",
    summary: "Long chat about family photos, her energy levels seemed normal.",
    transcript: "Dorothy: Hi there!\nAI: Hello Dorothy! How was your weekend?\nDorothy: It was wonderful! I spent the whole weekend looking through old family photos.\nAI: That sounds like a great time. How are your energy levels?\nDorothy: Quite good! I haven't felt tired at all.",
    flagged: false,
  },
  {
    id: "mock-4",
    name: "Uncle Arthur",
    title: "Arthur's Weekend Check-in",
    timestamp: new Date(Date.now() - 86400000 * 5).toISOString(),
    duration: "15m 20s",
    mood: "Positive",
    moodEmoji: "🤠",
    summary: "Arthur was doing well, talked about watching the football match.",
    transcript: "Arthur: Hello, who is this?\nAI: Hi Uncle Arthur, this is Hey Gran checking in.\nArthur: Oh, hello! I'm doing well, just watching the football match on the telly.\nAI: Nice! Who is playing?\nArthur: Arsenal, they are winning right now!",
    flagged: false,
  },
  {
    id: "mock-5",
    name: "Dorothy",
    title: "Dorothy's Morning Chat",
    timestamp: new Date(Date.now() - 86400000 * 7).toISOString(),
    duration: "10m 05s",
    mood: "Neutral",
    moodEmoji: "😐",
    summary: "General check-in, everything normal.",
    transcript: "Dorothy: Good morning.\nAI: Good morning Dorothy, how did you sleep?\nDorothy: I slept okay, nothing unusual.\nAI: Good to hear, everything normal today?\nDorothy: Yes, just going to read a book.",
    flagged: false,
  }
];
